// Builds the "Complete Strategy Ledger" — every strategy from every archived
// generation, with locked-in stats — and writes it into PAPER.md between markers.
//
//   npm run ledger
//
// This is the persistent evidence base for future strategy design: it records
// what was tried and how it actually did, so the btcbot "Statistician" reviewer
// can reason from real base rates instead of starting blind. Re-run it after
// archiving each new generation (cp results/snapshot.json -> results/genN/state.json).

import fs from 'node:fs';
import path from 'node:path';
import { config } from '../../config.js';
import { fmtSignedUSD } from '../util/money.js';

const RESULTS = config.resultsDir;
const PAPER = 'PAPER.md';
const START = '<!-- LEDGER:START -->';
const END = '<!-- LEDGER:END -->';

function loadGen(dir) {
  for (const name of ['state.json', 'snapshot.json']) {
    const f = path.join(dir, name);
    if (fs.existsSync(f)) {
      try {
        return JSON.parse(fs.readFileSync(f, 'utf8'));
      } catch {
        /* try next */
      }
    }
  }
  return null;
}

// Discover archived generations: results/gen<N>/ (manual runs) and
// results/evolution/gen<N>/holdout/ (evolver runs — judged on holdout, never tune).
function discoverGens() {
  const out = [];
  const scan = (dir, sub, tag) => {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const m = entry.isDirectory() && entry.name.match(/^gen(\d+)$/);
      if (!m) continue;
      const snap = loadGen(path.join(dir, entry.name, sub));
      if (snap?.rows?.length) out.push({ gen: Number(m[1]), snap, tag });
    }
  };
  scan(RESULTS, '.', '');
  // Evolver gens ran under realism friction — P/L not comparable to manual gens.
  scan(path.join(RESULTS, 'evolution'), 'holdout', ' · evolver holdout · realism friction');
  out.sort((a, b) => a.gen - b.gen);
  return out;
}

function summarize(rows) {
  const realized = (r) => r.realizedPnL;
  const combinedReal = rows.reduce((s, r) => s + realized(r), 0);
  const rnd = rows.filter((r) => r.family === 'RandomBaseline' || r.name.startsWith('RandomBaseline'));
  const rndVals = rnd.map(realized);
  const noiseLo = rndVals.length ? Math.min(...rndVals) : null;
  const noiseHi = rndVals.length ? Math.max(...rndVals) : null;
  const busts = rows.filter((r) => realized(r) <= -995).length;
  const up = rows.find((r) => /AlwaysSide\[side=Up\]/.test(r.name));
  const dn = rows.find((r) => /AlwaysSide\[side=Down\]/.test(r.name));
  let regime = 'mixed / undetermined';
  if (up && dn) {
    const d = realized(dn) - realized(up);
    regime = d > 200 ? 'down-leaning' : d < -200 ? 'up-leaning' : 'roughly flat';
  }
  return { combinedReal, noiseLo, noiseHi, busts, up, dn, regime };
}

function genSection(gen, snap, tag = '') {
  const rows = [...snap.rows].sort((a, b) => b.realizedPnL - a.realizedPnL);
  rows.forEach((r, i) => (r._rank = i + 1));
  const s = summarize(rows);
  const windows = snap.totals?.resolved ?? '?';

  const vsBand = (r) => {
    if (s.noiseLo == null) return '';
    if (r.realizedPnL > s.noiseHi) return '↑'; // beat the luckiest random bot
    if (r.realizedPnL < s.noiseLo) return '↓'; // worse than the unluckiest random bot
    return '≈'; // inside the noise band — indistinguishable from luck
  };

  const head =
    `### Generation ${gen}${tag} — ${rows.length} bots · ${windows} windows · ${s.regime} sample\n\n` +
    `- **Combined realized P/L:** ${fmtSignedUSD(s.combinedReal)}\n` +
    (s.noiseLo != null
      ? `- **Noise band** (luck floor↔ceiling, from identical random bots): ` +
        `[${fmtSignedUSD(s.noiseLo)}, ${fmtSignedUSD(s.noiseHi)}] — anything inside ≈ random\n`
      : '') +
    (s.up && s.dn
      ? `- **Direction controls:** AlwaysUp ${fmtSignedUSD(s.up.realizedPnL)} · AlwaysDown ${fmtSignedUSD(s.dn.realizedPnL)}\n`
      : '') +
    `- **Busts** (lost ≥ 99.5% of bankroll): ${s.busts}\n\n`;

  const tbl =
    `| # | Strategy | Realized | Total | Trades | Win% | Avg/Tr | vs? |\n` +
    `|--:|---|--:|--:|--:|--:|--:|:-:|\n` +
    rows
      .map(
        (r) =>
          `| ${r._rank} | ${r.name} | ${fmtSignedUSD(r.realizedPnL)} | ${fmtSignedUSD(r.totalPnL)} | ` +
          `${r.trades} | ${r.trades ? (r.winRate * 100).toFixed(0) + '%' : '—'} | ` +
          `${r.trades ? fmtSignedUSD(r.avgPerTrade) : '—'} | ${vsBand(r)} |`,
      )
      .join('\n');

  return head + tbl + '\n';
}

function build() {
  const gens = discoverGens();
  if (!gens.length) {
    console.log('No archived generations found under results/gen*/. Nothing to log.');
    return;
  }

  const body =
    `## Appendix B — Complete Strategy Ledger (all generations)\n\n` +
    `_Auto-generated by \`npm run ledger\`. Every strategy ever run, with its locked-in stats. ` +
    `This is the evidence base for designing future bots — hand it to the btcbot Statistician._\n\n` +
    `> **How to read it.** Judge on **Realized** P/L (settled), not Total (which includes open ` +
    `mark-to-mid). The **noise band** is the gap between the luckiest and unluckiest *identical* ` +
    `random bots in that run; any strategy inside it is statistically indistinguishable from luck. ` +
    `\`vs?\` flags whether a bot beat (↑), tied (≈), or lost to (↓) that band. A real edge must ` +
    `clear the band **and** repeat across regimes (compare the same family between generations).\n\n` +
    gens.map(({ gen, snap, tag }) => genSection(gen, snap, tag)).join('\n---\n\n');

  let paper = fs.existsSync(PAPER) ? fs.readFileSync(PAPER, 'utf8') : '# BotSim\n';
  const block = `${START}\n${body}${END}`;
  if (paper.includes(START) && paper.includes(END)) {
    paper = paper.replace(new RegExp(`${START}[\\s\\S]*${END}`), block);
  } else {
    paper = paper.replace(/\s*$/, '\n\n') + block + '\n';
  }
  fs.writeFileSync(PAPER, paper);

  const total = gens.reduce((n, g) => n + g.snap.rows.length, 0);
  console.log(`Ledger written to ${PAPER}: ${gens.length} generations, ${total} strategies logged.`);
  for (const { gen, snap } of gens) console.log(`  gen${gen}: ${snap.rows.length} bots, ${snap.totals?.resolved ?? '?'} windows`);
}

build();
